name: Python Flask App CI

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install dependencies
        run: |
          python -m venv venv  
          source venv/bin/activate  
          pip install -r requirements.txt  

      - name: Run Flask app
        run: |
          source venv/bin/activate
          flask run --host=0.0.0.0 --port=3000
