name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: make install

    - name: Run the Flask server
      run: |
        make run &
        sleep 60  # Sleep for 10 seconds to allow the server to start

    - name: Stop Flask server
      run: |
        pkill -f "flask run"
